spring:
  application:
    name: gestion-clientes

  profiles:
    active: local # cambia a 'docker' si corres dentro del contenedor

  jackson:
    time-zone: America/Guayaquil
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  messages:
    basename: ValidationMessages
    encoding: UTF-8

server:
  port: 8081
  servlet:
    context-path: /api/clientes

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
