spring:
  application:
    name: gestion-clientes
  profiles:
    active: local

server:
  port: 8081
  servlet:
    context-path: /api/gestion-clientes

management:
  endpoints:
    web:
      exposure:
        include: health,info
